services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - go_network
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - go_network
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go_network
networks:
  go_network:
    driver: bridge
volumes:
  postgres_data:
