/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateStoreImport } from './routes/create-store'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreateStoreRoute = CreateStoreImport.update({
  id: '/create-store',
  path: '/create-store',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-store': {
      id: '/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof CreateStoreImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-store': typeof CreateStoreRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-store': typeof CreateStoreRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-store': typeof CreateStoreRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-store'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-store'
  id: '__root__' | '/' | '/create-store'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateStoreRoute: typeof CreateStoreRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateStoreRoute: CreateStoreRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-store"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-store": {
      "filePath": "create-store.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
